// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gwresult.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GWResult_ActionType int32

const (
	GWResult_DEFAULT  GWResult_ActionType = 0
	GWResult_GW_INFO  GWResult_ActionType = 1
	GWResult_THREAT   GWResult_ActionType = 2
	GWResult_STRATEGY GWResult_ActionType = 3
)

var GWResult_ActionType_name = map[int32]string{
	0: "DEFAULT",
	1: "GW_INFO",
	2: "THREAT",
	3: "STRATEGY",
}

var GWResult_ActionType_value = map[string]int32{
	"DEFAULT":  0,
	"GW_INFO":  1,
	"THREAT":   2,
	"STRATEGY": 3,
}

func (x GWResult_ActionType) String() string {
	return proto.EnumName(GWResult_ActionType_name, int32(x))
}

func (GWResult_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{0, 0}
}

type GwInfoParam_Type int32

const (
	GwInfoParam_DEFAULT   GwInfoParam_Type = 0
	GwInfoParam_VSMART    GwInfoParam_Type = 1
	GwInfoParam_VHALO     GwInfoParam_Type = 2
	GwInfoParam_VWIFI     GwInfoParam_Type = 3
	GwInfoParam_VENUSHALO GwInfoParam_Type = 4
)

var GwInfoParam_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "VSMART",
	2: "VHALO",
	3: "VWIFI",
	4: "VENUSHALO",
}

var GwInfoParam_Type_value = map[string]int32{
	"DEFAULT":   0,
	"VSMART":    1,
	"VHALO":     2,
	"VWIFI":     3,
	"VENUSHALO": 4,
}

func (x GwInfoParam_Type) String() string {
	return proto.EnumName(GwInfoParam_Type_name, int32(x))
}

func (GwInfoParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1, 0}
}

type GwInfoParam_DeployMode int32

const (
	GwInfoParam_DEPLOYMODEDEFAULT GwInfoParam_DeployMode = 0
	GwInfoParam_ROUTEMODE         GwInfoParam_DeployMode = 1
	GwInfoParam_SWITCHMODE        GwInfoParam_DeployMode = 2
)

var GwInfoParam_DeployMode_name = map[int32]string{
	0: "DEPLOYMODEDEFAULT",
	1: "ROUTEMODE",
	2: "SWITCHMODE",
}

var GwInfoParam_DeployMode_value = map[string]int32{
	"DEPLOYMODEDEFAULT": 0,
	"ROUTEMODE":         1,
	"SWITCHMODE":        2,
}

func (x GwInfoParam_DeployMode) String() string {
	return proto.EnumName(GwInfoParam_DeployMode_name, int32(x))
}

func (GwInfoParam_DeployMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1, 1}
}

type ThreatParam_Item_Type int32

const (
	ThreatParam_Item_DEFAULT          ThreatParam_Item_Type = 0
	ThreatParam_Item_SITE             ThreatParam_Item_Type = 1
	ThreatParam_Item_IP               ThreatParam_Item_Type = 2
	ThreatParam_Item_DNSHIJACK        ThreatParam_Item_Type = 3
	ThreatParam_Item_UDEVICEWHITEIP   ThreatParam_Item_Type = 4
	ThreatParam_Item_UDEVICEWHITESITE ThreatParam_Item_Type = 5
	ThreatParam_Item_UDEVICEBLACKIP   ThreatParam_Item_Type = 6
	ThreatParam_Item_UDEVICEBLACKSITE ThreatParam_Item_Type = 7
	ThreatParam_Item_LANINTRUSION     ThreatParam_Item_Type = 8
	ThreatParam_Item_UDEVLANINTRUSION ThreatParam_Item_Type = 9
)

var ThreatParam_Item_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "SITE",
	2: "IP",
	3: "DNSHIJACK",
	4: "UDEVICEWHITEIP",
	5: "UDEVICEWHITESITE",
	6: "UDEVICEBLACKIP",
	7: "UDEVICEBLACKSITE",
	8: "LANINTRUSION",
	9: "UDEVLANINTRUSION",
}

var ThreatParam_Item_Type_value = map[string]int32{
	"DEFAULT":          0,
	"SITE":             1,
	"IP":               2,
	"DNSHIJACK":        3,
	"UDEVICEWHITEIP":   4,
	"UDEVICEWHITESITE": 5,
	"UDEVICEBLACKIP":   6,
	"UDEVICEBLACKSITE": 7,
	"LANINTRUSION":     8,
	"UDEVLANINTRUSION": 9,
}

func (x ThreatParam_Item_Type) String() string {
	return proto.EnumName(ThreatParam_Item_Type_name, int32(x))
}

func (ThreatParam_Item_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 0, 0}
}

type ThreatParam_Item_Status int32

const (
	ThreatParam_Item_UNKNOWN ThreatParam_Item_Status = 0
	ThreatParam_Item_FOUND   ThreatParam_Item_Status = 1
	ThreatParam_Item_PREVENT ThreatParam_Item_Status = 2
	ThreatParam_Item_WARNING ThreatParam_Item_Status = 3
)

var ThreatParam_Item_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "FOUND",
	2: "PREVENT",
	3: "WARNING",
}

var ThreatParam_Item_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"FOUND":   1,
	"PREVENT": 2,
	"WARNING": 3,
}

func (x ThreatParam_Item_Status) String() string {
	return proto.EnumName(ThreatParam_Item_Status_name, int32(x))
}

func (ThreatParam_Item_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 0, 1}
}

type StrategyParam_Type int32

const (
	StrategyParam_TYPEDEFAULT StrategyParam_Type = 0
	StrategyParam_WHITEMODE   StrategyParam_Type = 1
	StrategyParam_BLACKMODE   StrategyParam_Type = 2
)

var StrategyParam_Type_name = map[int32]string{
	0: "TYPEDEFAULT",
	1: "WHITEMODE",
	2: "BLACKMODE",
}

var StrategyParam_Type_value = map[string]int32{
	"TYPEDEFAULT": 0,
	"WHITEMODE":   1,
	"BLACKMODE":   2,
}

func (x StrategyParam_Type) String() string {
	return proto.EnumName(StrategyParam_Type_name, int32(x))
}

func (StrategyParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{3, 0}
}

type StrategyParam_HandleMode int32

const (
	StrategyParam_MODEDEFAULT    StrategyParam_HandleMode = 0
	StrategyParam_PREVENTWARNING StrategyParam_HandleMode = 1
	StrategyParam_WARNING        StrategyParam_HandleMode = 2
)

var StrategyParam_HandleMode_name = map[int32]string{
	0: "MODEDEFAULT",
	1: "PREVENTWARNING",
	2: "WARNING",
}

var StrategyParam_HandleMode_value = map[string]int32{
	"MODEDEFAULT":    0,
	"PREVENTWARNING": 1,
	"WARNING":        2,
}

func (x StrategyParam_HandleMode) String() string {
	return proto.EnumName(StrategyParam_HandleMode_name, int32(x))
}

func (StrategyParam_HandleMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{3, 1}
}

//小v请求的基本格式
type GWResult struct {
	ActionType           GWResult_ActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=protobuf.GWResult_ActionType" json:"action_type,omitempty"`
	Param                []byte              `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	GUID                 string              `protobuf:"bytes,3,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GWResult) Reset()         { *m = GWResult{} }
func (m *GWResult) String() string { return proto.CompactTextString(m) }
func (*GWResult) ProtoMessage()    {}
func (*GWResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{0}
}

func (m *GWResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GWResult.Unmarshal(m, b)
}
func (m *GWResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GWResult.Marshal(b, m, deterministic)
}
func (m *GWResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GWResult.Merge(m, src)
}
func (m *GWResult) XXX_Size() int {
	return xxx_messageInfo_GWResult.Size(m)
}
func (m *GWResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GWResult.DiscardUnknown(m)
}

var xxx_messageInfo_GWResult proto.InternalMessageInfo

func (m *GWResult) GetActionType() GWResult_ActionType {
	if m != nil {
		return m.ActionType
	}
	return GWResult_DEFAULT
}

func (m *GWResult) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *GWResult) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

type GwInfoParam struct {
	Version              string                    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartTime            uint32                    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FirmwareVersion      string                    `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	HardwareModel        string                    `protobuf:"bytes,4,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	Module               []*GwInfoParam_ModuleItem `protobuf:"bytes,5,rep,name=module,proto3" json:"module,omitempty"`
	SupplyId             string                    `protobuf:"bytes,6,opt,name=supply_id,json=supplyId,proto3" json:"supply_id,omitempty"`
	UpRouterIp           string                    `protobuf:"bytes,7,opt,name=up_router_ip,json=upRouterIp,proto3" json:"up_router_ip,omitempty"`
	Ip                   string                    `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Type                 GwInfoParam_Type          `protobuf:"varint,9,opt,name=type,proto3,enum=protobuf.GwInfoParam_Type" json:"type,omitempty"`
	Mac                  string                    `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	Timestamp            uint32                    `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeployMode           GwInfoParam_DeployMode    `protobuf:"varint,12,opt,name=deploy_mode,json=deployMode,proto3,enum=protobuf.GwInfoParam_DeployMode" json:"deploy_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GwInfoParam) Reset()         { *m = GwInfoParam{} }
func (m *GwInfoParam) String() string { return proto.CompactTextString(m) }
func (*GwInfoParam) ProtoMessage()    {}
func (*GwInfoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1}
}

func (m *GwInfoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwInfoParam.Unmarshal(m, b)
}
func (m *GwInfoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwInfoParam.Marshal(b, m, deterministic)
}
func (m *GwInfoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwInfoParam.Merge(m, src)
}
func (m *GwInfoParam) XXX_Size() int {
	return xxx_messageInfo_GwInfoParam.Size(m)
}
func (m *GwInfoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GwInfoParam.DiscardUnknown(m)
}

var xxx_messageInfo_GwInfoParam proto.InternalMessageInfo

func (m *GwInfoParam) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GwInfoParam) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GwInfoParam) GetFirmwareVersion() string {
	if m != nil {
		return m.FirmwareVersion
	}
	return ""
}

func (m *GwInfoParam) GetHardwareModel() string {
	if m != nil {
		return m.HardwareModel
	}
	return ""
}

func (m *GwInfoParam) GetModule() []*GwInfoParam_ModuleItem {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *GwInfoParam) GetSupplyId() string {
	if m != nil {
		return m.SupplyId
	}
	return ""
}

func (m *GwInfoParam) GetUpRouterIp() string {
	if m != nil {
		return m.UpRouterIp
	}
	return ""
}

func (m *GwInfoParam) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GwInfoParam) GetType() GwInfoParam_Type {
	if m != nil {
		return m.Type
	}
	return GwInfoParam_DEFAULT
}

func (m *GwInfoParam) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GwInfoParam) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GwInfoParam) GetDeployMode() GwInfoParam_DeployMode {
	if m != nil {
		return m.DeployMode
	}
	return GwInfoParam_DEPLOYMODEDEFAULT
}

type GwInfoParam_ModuleItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwInfoParam_ModuleItem) Reset()         { *m = GwInfoParam_ModuleItem{} }
func (m *GwInfoParam_ModuleItem) String() string { return proto.CompactTextString(m) }
func (*GwInfoParam_ModuleItem) ProtoMessage()    {}
func (*GwInfoParam_ModuleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1, 0}
}

func (m *GwInfoParam_ModuleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Unmarshal(m, b)
}
func (m *GwInfoParam_ModuleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Marshal(b, m, deterministic)
}
func (m *GwInfoParam_ModuleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwInfoParam_ModuleItem.Merge(m, src)
}
func (m *GwInfoParam_ModuleItem) XXX_Size() int {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Size(m)
}
func (m *GwInfoParam_ModuleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GwInfoParam_ModuleItem.DiscardUnknown(m)
}

var xxx_messageInfo_GwInfoParam_ModuleItem proto.InternalMessageInfo

func (m *GwInfoParam_ModuleItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GwInfoParam_ModuleItem) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

//威胁类型
type ThreatParam struct {
	ThreatItem           []*ThreatParam_Item `protobuf:"bytes,1,rep,name=threat_item,json=threatItem,proto3" json:"threat_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ThreatParam) Reset()         { *m = ThreatParam{} }
func (m *ThreatParam) String() string { return proto.CompactTextString(m) }
func (*ThreatParam) ProtoMessage()    {}
func (*ThreatParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2}
}

func (m *ThreatParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreatParam.Unmarshal(m, b)
}
func (m *ThreatParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreatParam.Marshal(b, m, deterministic)
}
func (m *ThreatParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatParam.Merge(m, src)
}
func (m *ThreatParam) XXX_Size() int {
	return xxx_messageInfo_ThreatParam.Size(m)
}
func (m *ThreatParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatParam.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatParam proto.InternalMessageInfo

func (m *ThreatParam) GetThreatItem() []*ThreatParam_Item {
	if m != nil {
		return m.ThreatItem
	}
	return nil
}

//威胁事件object,
type ThreatParam_Item struct {
	SrcMac               string                  `protobuf:"bytes,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	ThreatType           ThreatParam_Item_Type   `protobuf:"varint,2,opt,name=threat_type,json=threatType,proto3,enum=protobuf.ThreatParam_Item_Type" json:"threat_type,omitempty"`
	Content              string                  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ThreatStatus         ThreatParam_Item_Status `protobuf:"varint,4,opt,name=threat_status,json=threatStatus,proto3,enum=protobuf.ThreatParam_Item_Status" json:"threat_status,omitempty"`
	AttactTime           uint32                  `protobuf:"varint,5,opt,name=attact_time,json=attactTime,proto3" json:"attact_time,omitempty"`
	SrcIp                string                  `protobuf:"bytes,6,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                string                  `protobuf:"bytes,7,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ThreatParam_Item) Reset()         { *m = ThreatParam_Item{} }
func (m *ThreatParam_Item) String() string { return proto.CompactTextString(m) }
func (*ThreatParam_Item) ProtoMessage()    {}
func (*ThreatParam_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 0}
}

func (m *ThreatParam_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreatParam_Item.Unmarshal(m, b)
}
func (m *ThreatParam_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreatParam_Item.Marshal(b, m, deterministic)
}
func (m *ThreatParam_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatParam_Item.Merge(m, src)
}
func (m *ThreatParam_Item) XXX_Size() int {
	return xxx_messageInfo_ThreatParam_Item.Size(m)
}
func (m *ThreatParam_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatParam_Item.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatParam_Item proto.InternalMessageInfo

func (m *ThreatParam_Item) GetSrcMac() string {
	if m != nil {
		return m.SrcMac
	}
	return ""
}

func (m *ThreatParam_Item) GetThreatType() ThreatParam_Item_Type {
	if m != nil {
		return m.ThreatType
	}
	return ThreatParam_Item_DEFAULT
}

func (m *ThreatParam_Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ThreatParam_Item) GetThreatStatus() ThreatParam_Item_Status {
	if m != nil {
		return m.ThreatStatus
	}
	return ThreatParam_Item_UNKNOWN
}

func (m *ThreatParam_Item) GetAttactTime() uint32 {
	if m != nil {
		return m.AttactTime
	}
	return 0
}

func (m *ThreatParam_Item) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *ThreatParam_Item) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

// 小V 当前策略的状态
type StrategyParam struct {
	StrategyId           string                   `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	HandleMode           StrategyParam_HandleMode `protobuf:"varint,2,opt,name=handle_mode,json=handleMode,proto3,enum=protobuf.StrategyParam_HandleMode" json:"handle_mode,omitempty"`
	DefenseType          StrategyParam_Type       `protobuf:"varint,3,opt,name=defense_type,json=defenseType,proto3,enum=protobuf.StrategyParam_Type" json:"defense_type,omitempty"`
	Enable               bool                     `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StrategyParam) Reset()         { *m = StrategyParam{} }
func (m *StrategyParam) String() string { return proto.CompactTextString(m) }
func (*StrategyParam) ProtoMessage()    {}
func (*StrategyParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{3}
}

func (m *StrategyParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyParam.Unmarshal(m, b)
}
func (m *StrategyParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyParam.Marshal(b, m, deterministic)
}
func (m *StrategyParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyParam.Merge(m, src)
}
func (m *StrategyParam) XXX_Size() int {
	return xxx_messageInfo_StrategyParam.Size(m)
}
func (m *StrategyParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyParam.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyParam proto.InternalMessageInfo

func (m *StrategyParam) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *StrategyParam) GetHandleMode() StrategyParam_HandleMode {
	if m != nil {
		return m.HandleMode
	}
	return StrategyParam_MODEDEFAULT
}

func (m *StrategyParam) GetDefenseType() StrategyParam_Type {
	if m != nil {
		return m.DefenseType
	}
	return StrategyParam_TYPEDEFAULT
}

func (m *StrategyParam) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func init() {
	proto.RegisterEnum("protobuf.GWResult_ActionType", GWResult_ActionType_name, GWResult_ActionType_value)
	proto.RegisterEnum("protobuf.GwInfoParam_Type", GwInfoParam_Type_name, GwInfoParam_Type_value)
	proto.RegisterEnum("protobuf.GwInfoParam_DeployMode", GwInfoParam_DeployMode_name, GwInfoParam_DeployMode_value)
	proto.RegisterEnum("protobuf.ThreatParam_Item_Type", ThreatParam_Item_Type_name, ThreatParam_Item_Type_value)
	proto.RegisterEnum("protobuf.ThreatParam_Item_Status", ThreatParam_Item_Status_name, ThreatParam_Item_Status_value)
	proto.RegisterEnum("protobuf.StrategyParam_Type", StrategyParam_Type_name, StrategyParam_Type_value)
	proto.RegisterEnum("protobuf.StrategyParam_HandleMode", StrategyParam_HandleMode_name, StrategyParam_HandleMode_value)
	proto.RegisterType((*GWResult)(nil), "protobuf.GWResult")
	proto.RegisterType((*GwInfoParam)(nil), "protobuf.GwInfoParam")
	proto.RegisterType((*GwInfoParam_ModuleItem)(nil), "protobuf.GwInfoParam.ModuleItem")
	proto.RegisterType((*ThreatParam)(nil), "protobuf.ThreatParam")
	proto.RegisterType((*ThreatParam_Item)(nil), "protobuf.ThreatParam.Item")
	proto.RegisterType((*StrategyParam)(nil), "protobuf.StrategyParam")
}

func init() { proto.RegisterFile("gwresult.proto", fileDescriptor_0afa8f4c35ece810) }

var fileDescriptor_0afa8f4c35ece810 = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6f, 0xe2, 0x56,
	0x14, 0x1d, 0x1b, 0x63, 0xf0, 0x35, 0x30, 0xaf, 0x4f, 0x33, 0xad, 0x95, 0xce, 0x28, 0xd4, 0x52,
	0xa5, 0x74, 0xc3, 0x22, 0x55, 0xa5, 0x6a, 0x2a, 0x4d, 0xc7, 0x13, 0x1c, 0x78, 0x4d, 0x30, 0xc8,
	0x18, 0x50, 0x56, 0xc8, 0xc1, 0x2f, 0x13, 0x4b, 0x18, 0x5b, 0xf6, 0xa3, 0x11, 0xcb, 0x6e, 0xfb,
	0x6b, 0xba, 0xea, 0x3f, 0xe8, 0xb6, 0xbf, 0xa9, 0xf2, 0xb5, 0xcd, 0x87, 0x3a, 0x99, 0x15, 0xf7,
	0x1e, 0x1f, 0x5f, 0x5f, 0xce, 0x39, 0xef, 0x41, 0xe7, 0xd3, 0x53, 0xca, 0xb3, 0xed, 0x5a, 0xf4,
	0x92, 0x34, 0x16, 0x31, 0x6d, 0xe2, 0xcf, 0xfd, 0xf6, 0xc1, 0xfc, 0x5b, 0x82, 0xe6, 0x60, 0xe1,
	0xe2, 0x43, 0xfa, 0x1e, 0x74, 0x7f, 0x25, 0xc2, 0x78, 0xb3, 0x14, 0xbb, 0x84, 0x1b, 0x52, 0x57,
	0xba, 0xe8, 0x5c, 0xbe, 0xed, 0x55, 0xe4, 0x5e, 0x45, 0xec, 0x59, 0xc8, 0xf2, 0x76, 0x09, 0x77,
	0xc1, 0xdf, 0xd7, 0xf4, 0x15, 0xd4, 0x13, 0x3f, 0xf5, 0x23, 0x43, 0xee, 0x4a, 0x17, 0x2d, 0xb7,
	0x68, 0x28, 0x05, 0x65, 0x30, 0x63, 0x7d, 0xa3, 0xd6, 0x95, 0x2e, 0x34, 0x17, 0x6b, 0xf3, 0x03,
	0xc0, 0x61, 0x06, 0xd5, 0xa1, 0xd1, 0xb7, 0xaf, 0xad, 0xd9, 0xad, 0x47, 0x5e, 0xe4, 0xcd, 0x60,
	0xb1, 0x64, 0xce, 0xf5, 0x98, 0x48, 0x14, 0x40, 0xf5, 0x86, 0xae, 0x6d, 0x79, 0x44, 0xa6, 0x2d,
	0x68, 0x4e, 0x3d, 0xd7, 0xf2, 0xec, 0xc1, 0x1d, 0xa9, 0x99, 0x7f, 0xd6, 0x41, 0x1f, 0x3c, 0xb1,
	0xcd, 0x43, 0x3c, 0xc1, 0xaf, 0x18, 0xd0, 0xf8, 0x9d, 0xa7, 0x59, 0x18, 0x6f, 0x70, 0x6f, 0xcd,
	0xad, 0x5a, 0xfa, 0x16, 0x20, 0x13, 0x7e, 0x2a, 0x96, 0x22, 0x8c, 0x38, 0xae, 0xd6, 0x76, 0x35,
	0x44, 0xbc, 0x30, 0xe2, 0xf4, 0x07, 0x20, 0x0f, 0x61, 0x1a, 0x3d, 0xf9, 0x29, 0x5f, 0x56, 0x13,
	0x8a, 0x55, 0x5f, 0x56, 0xf8, 0xbc, 0x9c, 0xf4, 0x3d, 0x74, 0x1e, 0xfd, 0x34, 0x40, 0x6a, 0x14,
	0x07, 0x7c, 0x6d, 0x28, 0x48, 0x6c, 0x57, 0xe8, 0x28, 0x07, 0xe9, 0xcf, 0xa0, 0x46, 0x71, 0xb0,
	0x5d, 0x73, 0xa3, 0xde, 0xad, 0x5d, 0xe8, 0x97, 0xdd, 0x23, 0x05, 0x0f, 0x1b, 0xf7, 0x46, 0xc8,
	0x61, 0x82, 0x47, 0x6e, 0xc9, 0xa7, 0xdf, 0x82, 0x96, 0x6d, 0x93, 0x64, 0xbd, 0x5b, 0x86, 0x81,
	0xa1, 0xe2, 0xec, 0x66, 0x01, 0xb0, 0x80, 0x76, 0xa1, 0xb5, 0x4d, 0x96, 0x69, 0xbc, 0x15, 0x3c,
	0x5d, 0x86, 0x89, 0xd1, 0xc0, 0xe7, 0xb0, 0x4d, 0x5c, 0x84, 0x58, 0x42, 0x3b, 0x20, 0x87, 0x89,
	0xd1, 0x44, 0x5c, 0x0e, 0x13, 0xda, 0x03, 0x05, 0x8d, 0xd4, 0xd0, 0xc8, 0xb3, 0xcf, 0xaf, 0x81,
	0x2e, 0x22, 0x8f, 0x12, 0xa8, 0x45, 0xfe, 0xca, 0x00, 0x1c, 0x90, 0x97, 0xf4, 0x0d, 0x68, 0xb9,
	0x6a, 0x99, 0xf0, 0xa3, 0xc4, 0xd0, 0x0b, 0xe9, 0xf6, 0x00, 0xb5, 0x40, 0x0f, 0x78, 0xb2, 0x8e,
	0x77, 0xa8, 0x86, 0xd1, 0xc2, 0xcf, 0x3c, 0xf3, 0x6f, 0xfb, 0x48, 0xcc, 0x05, 0x72, 0x21, 0xd8,
	0xd7, 0x67, 0xef, 0x00, 0x0e, 0x3a, 0xe4, 0x51, 0xd9, 0xf8, 0x11, 0x2f, 0x1d, 0xc4, 0xfa, 0xd8,
	0x58, 0xf9, 0xc4, 0x58, 0xb3, 0x0f, 0xca, 0xff, 0xe3, 0x03, 0xa0, 0xce, 0xa7, 0x23, 0xcb, 0xf5,
	0x88, 0x44, 0x35, 0xa8, 0xcf, 0x87, 0xd6, 0xed, 0x98, 0xc8, 0x58, 0x2e, 0xd8, 0x35, 0x23, 0x35,
	0xda, 0x06, 0x6d, 0x6e, 0x3b, 0xb3, 0x29, 0x3e, 0x51, 0xcc, 0x8f, 0x00, 0x87, 0xdd, 0xe8, 0x6b,
	0xf8, 0xaa, 0x6f, 0x4f, 0x6e, 0xc7, 0x77, 0xa3, 0x71, 0xdf, 0x3e, 0x4c, 0x6d, 0x83, 0xe6, 0x8e,
	0x67, 0x9e, 0x9d, 0xa3, 0x44, 0xa2, 0x1d, 0x80, 0xe9, 0x82, 0x79, 0x57, 0x43, 0xec, 0x65, 0xf3,
	0x5f, 0x05, 0x74, 0xef, 0x31, 0xe5, 0xbe, 0x28, 0xc2, 0xf8, 0x0b, 0xe8, 0x02, 0xdb, 0x65, 0x28,
	0x78, 0x64, 0x48, 0x18, 0x83, 0x23, 0xfd, 0x8f, 0xb8, 0x3d, 0x0c, 0x00, 0x14, 0xf4, 0xbc, 0x3e,
	0xfb, 0x43, 0x01, 0x05, 0xd5, 0xf8, 0x06, 0x1a, 0x59, 0xba, 0x5a, 0xe6, 0x96, 0x14, 0x82, 0xa8,
	0x59, 0xba, 0x1a, 0xf9, 0x2b, 0xfa, 0x61, 0x3f, 0x1e, 0xed, 0x95, 0x51, 0xf7, 0xf3, 0xe7, 0xc7,
	0x17, 0x1e, 0x97, 0xdf, 0x40, 0xc9, 0x0c, 0x68, 0xac, 0xe2, 0x8d, 0xe0, 0x1b, 0x51, 0x66, 0xbd,
	0x6a, 0xe9, 0x35, 0xb4, 0xcb, 0xd9, 0x99, 0xf0, 0xc5, 0x36, 0xc3, 0x88, 0x77, 0x2e, 0xbf, 0xfb,
	0xc2, 0xf4, 0x29, 0x12, 0xdd, 0x56, 0xf1, 0x5e, 0xd1, 0xd1, 0x73, 0xd0, 0x7d, 0x21, 0xfc, 0x55,
	0x79, 0xec, 0xea, 0x98, 0x1d, 0x28, 0x20, 0x3c, 0x77, 0xaf, 0x21, 0xff, 0x3b, 0x79, 0x90, 0x8b,
	0xa0, 0xd7, 0xb3, 0x74, 0xc5, 0x92, 0x1c, 0x0e, 0x32, 0x71, 0xc8, 0x77, 0x3d, 0xc8, 0x04, 0x4b,
	0xcc, 0xbf, 0xa4, 0xcf, 0x99, 0xdd, 0x04, 0x65, 0xca, 0xbc, 0xdc, 0x11, 0x15, 0x64, 0x36, 0x21,
	0x72, 0x6e, 0x54, 0xdf, 0x99, 0x0e, 0xd9, 0x6f, 0xd6, 0xd5, 0x0d, 0xa9, 0x51, 0x0a, 0x9d, 0x59,
	0xdf, 0x9e, 0xb3, 0x2b, 0x7b, 0x31, 0x64, 0x9e, 0xcd, 0x26, 0x44, 0xa1, 0xaf, 0x80, 0x1c, 0x63,
	0x38, 0xa0, 0x7e, 0xc4, 0xfc, 0x78, 0x6b, 0x5d, 0xdd, 0xb0, 0x09, 0x51, 0x8f, 0x98, 0x88, 0x21,
	0xb3, 0x41, 0x09, 0xb4, 0x6e, 0x2d, 0x87, 0x39, 0x9e, 0x3b, 0x9b, 0xb2, 0xb1, 0x43, 0x9a, 0x15,
	0xef, 0x04, 0xd5, 0xcc, 0x77, 0xa0, 0x96, 0x5a, 0xe8, 0xd0, 0x98, 0x39, 0x37, 0xce, 0x78, 0xe1,
	0x90, 0x17, 0x79, 0x12, 0xaf, 0xc7, 0x33, 0xa7, 0x4f, 0xa4, 0x1c, 0x9f, 0xb8, 0xf6, 0xdc, 0x76,
	0xf2, 0xeb, 0x4d, 0x87, 0xc6, 0xc2, 0x72, 0x1d, 0xe6, 0x0c, 0x48, 0xcd, 0xfc, 0x47, 0x86, 0xf6,
	0x54, 0xa4, 0xbe, 0xe0, 0x9f, 0x76, 0x45, 0xa4, 0xce, 0x41, 0xcf, 0x4a, 0x20, 0xbf, 0x1c, 0x8a,
	0x40, 0x40, 0x05, 0xb1, 0x80, 0x5e, 0x81, 0xfe, 0xe8, 0x6f, 0x82, 0x75, 0x71, 0x35, 0x95, 0xa1,
	0x30, 0x0f, 0xb6, 0x9d, 0x8c, 0xeb, 0x0d, 0x91, 0x5a, 0x1c, 0xc7, 0xc7, 0x7d, 0x4d, 0x7f, 0x85,
	0x56, 0xc0, 0x1f, 0xf8, 0x26, 0xe3, 0x45, 0xb4, 0x6a, 0x38, 0xe5, 0xcd, 0x73, 0x53, 0x30, 0x57,
	0x7a, 0xf9, 0x06, 0xda, 0xf3, 0x35, 0xa8, 0x7c, 0xe3, 0xdf, 0xaf, 0x39, 0xe6, 0xa6, 0xe9, 0x96,
	0x9d, 0xf9, 0x53, 0x69, 0xdf, 0x4b, 0xd0, 0xbd, 0xbb, 0xc9, 0xe9, 0xc9, 0x42, 0x1b, 0xca, 0x93,
	0xd5, 0x06, 0x0d, 0xb5, 0x2e, 0x0f, 0xd6, 0x7b, 0x80, 0xc3, 0xa6, 0xf9, 0xcb, 0xa7, 0xc7, 0x92,
	0x42, 0xa7, 0x14, 0xb0, 0x92, 0x4e, 0x3a, 0xd6, 0x51, 0xbe, 0x57, 0x71, 0xf1, 0x1f, 0xff, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0x55, 0x2e, 0x35, 0x01, 0x07, 0x00, 0x00,
}
